### ISSUE TITLE
Documentation on Java missing?

### ISSUE THREAD

**Issue by maniac0s** [NordicID/ar8x_samples#3]
I can not manage to create the java app using this example. As soon as I compile the app under Windows the app fails to start. I tried java 11 and java 8

JavaMQTTSample@SampoS2K190600757:~$ ./run start
Error occurred during initialization of VM
java/lang/NoClassDefFoundError: java/lang/Object

When I use the original zip folder, the app runs fine. Just a mere compilation without changing the source code makes it fail to start.

What version of javac exactly do I need to make this run?

Edit: Even trying to run java from the app fails.

JavaMQTTSample@SampoS2K190600757:~$ java/bin/java
Error occurred during initialization of VM
java/lang/NoClassDefFoundError: java/lang/Object
JavaMQTTSample@SampoS2K190600757:~$ java/jre/bin/java
Error occurred during initialization of VM
java/lang/NoClassDefFoundError: java/lang/Object

**Comment by Tychus** [comment]
Hi @maniac0s 

The application should work now there were some missing jar files preventing it from starting correctly.
