### ISSUE TITLE
Multiple UriTemplate with same signature in WcfInterface

### ISSUE THREAD

**Issue by KhachQuy** [NordicID/ar8x_samples#6]
As I was trying to run some of the sample applications, I ran into an issue with **6. LLRP_sample**.

In WcfInterface.cs file, there are two methods share the same UriTemplate and Method.

```csharp
[OperationContract, WebInvoke(Method = WebRequestMethods.Http.Post,
UriTemplate = "/GetDeviceSetup",
RequestFormat = WebMessageFormat.Json, ResponseFormat = WebMessageFormat.Json)
]
DeviceStatusObject GetDeviceSetup(string deviceId);
```

```csharp
[OperationContract, WebInvoke(Method = WebRequestMethods.Http.Post,
UriTemplate = "/GetDeviceSetup",
RequestFormat = WebMessageFormat.Json, ResponseFormat = WebMessageFormat.Json)]
NormaStatus GetDeviceStatus(string deviceId);
```

I believe the second method should be `/GetDeviceStatus`.
This results in runtime error below:
`
Error Message [In contract 'WcfInterface', there are multiple operations with Method 'POST' and
 a UriTemplate that is equivalent to '/GetDeviceSetup'. Each operation requires a unique combin
ation of UriTemplate and Method to unambiguously dispatch messages. Use WebGetAttribute or WebI
nvokeAttribute to alter the UriTemplate and Method values of an operation.]
`

**Comment by mikkonid** [comment]
You're right indeed, thanks.

Fixed:
https://github.com/NordicID/ar8x_samples/commit/eb5eaa76a126491f91cb72d1863ca70030e98f6d
