### ISSUE TITLE
Error while checking if provided path is a directory

### ISSUE THREAD

**Issue by TheNeverK** [NordicID/ar8x_samples#7]
Hi,
I've been tasked with some research about NUR SDK and AR85 and because of that I've been reading documentation and trying out different examples. When I was trying to sign a folder directly from this repository, as shown in the docs and batch scripts, I got an `System.UnauthorizedAccessException`. I tried different things, but finally I decided to look into the source code of the `ar_signtool_cli`. A quick debugging session showed that the culprit is the line https://github.com/NordicID/ar8x_samples/blob/931bccafdeaddbdc10205dcb5809a85efe04f9af/tools/ar_signtool_cli/ar_signtool_cli/Program.cs#L42 which doesn't allow for any other file attribute than `Directory`. It happens that i've cloned the repository into a compressed folder (builtin Windows compression). As such, the `SignFolder` method was never called, only the `SignZipFile`, which of course threw exception, as (I assume) it expects a single Zip file.
If the compression or other attributes are not allowed there should be a clean message about it. Otherwise this issue can be fixed replacing the check wit a code like 
```C#
if (inputFi.Attributes.HasFlag(FileAttributes.Directory))
```

I would make a PR, but I cannot test if compression or this change cause problems, as I don't have the necessary hardware yet. Sorry.

**Comment by mikkonid** [comment]
Good catch. 
Fixed in https://github.com/NordicID/ar8x_samples/commit/2353ad33e5ef84c96dd8e932344539536246c00d 

Thanks.
